"""add meal source fields

Revision ID: 2c1770c6ea35
Revises: 2975aa7b59b6
Create Date: 2026-08-26 11:46:46.763735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c1770c6ea35"
down_revision: Union[str, Sequence[str], None] = "2975aa7b59b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meals", sa.Column("source_name", sa.String(length=200), nullable=False)
    )
    op.add_column("meals", sa.Column("source_reference", sa.Text(), nullable=True))
    op.add_column(
        "meals",
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_check_constraint(
        "ck_meals_source_name_not_blank", "meals", "length(trim(source_name)) > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_meals_source_name_not_blank", "meals", type_="check")
    op.drop_column("meals", "source_retrieved_at")
    op.drop_column("meals", "source_reference")
    op.drop_column("meals", "source_name")
    # ### end Alembic commands ###
