"""add food aliases

Revision ID: 737e94a4f13c
Revises: 2c1770c6ea35
Create Date: 2026-08-26 15:51:46.511546

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "737e94a4f13c"
down_revision: Union[str, Sequence[str], None] = "2c1770c6ea35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food_aliases",
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("external_name", sa.String(length=200), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "length(trim(external_name)) > 0",
            name="ck_food_aliases_external_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(normalized_name)) > 0",
            name="ck_food_aliases_normalized_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(source_name)) > 0",
            name="ck_food_aliases_source_name_not_blank",
        ),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_name", "normalized_name"),
    )
    op.create_index(
        op.f("ix_food_aliases_food_id"), "food_aliases", ["food_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_food_aliases_food_id"), table_name="food_aliases")
    op.drop_table("food_aliases")
    # ### end Alembic commands ###
