"""keep imported recipe measures

Revision ID: 7d0e485e821c
Revises: 737e94a4f13c
Create Date: 2026-08-26 16:17:49.065301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d0e485e821c"
down_revision: Union[str, Sequence[str], None] = "737e94a4f13c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal_ingredients",
        sa.Column("source_measure", sa.String(length=100), nullable=True),
    )
    op.add_column("meals", sa.Column("source_servings", sa.Integer(), nullable=True))
    op.create_check_constraint(
        "ck_meals_source_servings_positive",
        "meals",
        "source_servings IS NULL OR source_servings > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_meals_source_servings_positive", "meals", type_="check")
    op.drop_column("meals", "source_servings")
    op.drop_column("meal_ingredients", "source_measure")
    # ### end Alembic commands ###
