"""add food portions

Revision ID: eb40263d875e
Revises: 7d0e485e821c
Create Date: 2026-08-26 16:56:29.931503

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb40263d875e"
down_revision: Union[str, Sequence[str], None] = "7d0e485e821c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food_portions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("modifier", sa.String(length=200), nullable=True),
        sa.Column("gram_weight", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("source_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_food_portions_amount_positive"),
        sa.CheckConstraint(
            "gram_weight > 0", name="ck_food_portions_gram_weight_positive"
        ),
        sa.CheckConstraint(
            "length(trim(source_name)) > 0",
            name="ck_food_portions_source_name_not_blank",
        ),
        sa.CheckConstraint(
            "length(trim(unit)) > 0", name="ck_food_portions_unit_not_blank"
        ),
        sa.ForeignKeyConstraint(["food_id"], ["foods.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_portions_food_id"), "food_portions", ["food_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_food_portions_food_id"), table_name="food_portions")
    op.drop_table("food_portions")
    # ### end Alembic commands ###
